services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

    Mindy\Bundle\FormBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    Mindy\Bundle\FormBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags: ['form.type']

    Mindy\Bundle\FormBundle\Form\Extension\CheckboxExtension:
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType }

    Mindy\Bundle\FormBundle\Form\Extension\HelpExtension:
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Mindy\Bundle\FormBundle\Form\Extension\QuerySetExtension:
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    Mindy\Bundle\FormBundle\Form\Extension\TooltipExtension:
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Symfony\Component\Form\FormRenderer:
        public: true
