services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

        \Swift_Events_SendListener:
            public: true
            tags: ['swiftmailer.default.plugin']

    Mindy\Bundle\FormBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    Symfony\Component\Form\FormRenderer:
        public: true
